language: cpp

branches:
  only:
    - master

dist: bionic

addons:
  apt:
    packages:
    - cmake
    - make
    - g++
    - pkg-config

# Build steps
script:
  - ./build_simple.sh
  - ./wsjcpp-safe-scripting scripts.wsjcpp/generate.WSJCppSafeScriptingProc TestProc
  - cd unit-tests.wsjcpp
  - ./build_simple.sh
  - ./unit-tests